name: teledart
description: A Dart library interfacing with the latest Telegram Bot API.
version: 0.2.0
homepage: https://github.com/DinoLeung/TeleDart
issue_tracker: https://github.com/DinoLeung/TeleDart/issues

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  json_annotation: ^4.0.1
  http: ^0.13.3

dev_dependencies:
  test: ^1.17.9
  build_runner: ^2.0.5
  json_serializable: ^4.1.3
  pedantic: ^1.11.1
